version: '3.8'

services:
  # PHP-FPM контейнер для Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./public:/var/www/symfony/public
    environment:
      - APP_ENV=dev
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    networks:
      - symfony

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/symfony/public
    ports:
      - "8081:80"
    depends_on:
      - php
    networks:
      - symfony

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data:
